Freitag/restaurant_app/config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: [:create]
    member do
      get :chef_info
    end
  end

end

Freitag/restaurant_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class


end

Freitag/restaurant_app/app/models/chef.rb
class Chef < ApplicationRecord
  belongs_to :restaurant
end

Freitag/restaurant_app/app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews
  has_one :chef
  enum :kitchen_type, %w"normal veggie vegan"
end

Freitag/restaurant_app/app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
end

Freitag/restaurant_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

Freitag/restaurant_app/app/controllers/restaurant_controller.rb
class RestaurantController < ApplicationController
end

Freitag/restaurant_app/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end


  def show
    @restaurant = Restaurant.includes(:reviews).find(params[:id])
    @review = Review.new
  end


  def new
    @restaurant = Restaurant.new
  end


  def create
    rest = Restaurant.new(restaurant_params)
    rest.save
    redirect_to restaurants_path
  end


  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    restaurant = Restaurant.find(params[:id])
    restaurant.save

    redirect_to restaurant_path(restaurant)
  end

  def destroy
    restaurant = Restaurant.find(params[:id])
    restaurant.destroy

    redirect_to restaurants_path
  end


  def chef_info
    puts "CHEF INFO _____+++++++++++==+______ "
    p params
  end


  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address)
  end
end

Freitag/restaurant_app/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController


  def create
    redirect_to restaurants_path
  end
end

Freitag/restaurant_app/app/helpers/application_helper.rb
module ApplicationHelper

  def cheff_info(restaurant)
    "<h1> cheff info helper </h1>"
  end
end

Freitag/restaurant_app/app/helpers/restaurant_helper.rb
module RestaurantHelper
end

Freitag/restaurant_app/app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

Freitag/restaurant_app/app/helpers/reviews_helper.rb
module ReviewsHelper
end

Freitag/restaurant_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Restaurant App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <main class="container mt-5"></main>
    <%= yield %>
  </body>
</html>

Freitag/restaurant_app/app/views/restaurants/_form.html.erb
<%=form_with model:@restaurant do |form|%>
  <%=form.label :name  %>
  <%=form.text_field :name, placeholder: "Restaurant Name" %>
  <%=form.label :address %>
  <%=form.text_field :address, placeholder: "Restaurant Address" %>


  <%=form.submit "Create Restaurant" %>
<% end %>

Freitag/restaurant_app/app/views/restaurants/_restaurant.html.erb
  <li id=restaurant.id >
    <%= link_to restaurant.name, restaurant_path(restaurant) %>
    <p>
    <%= turbo_frame_tag id="<%=restaurant_#{@restaurant.id}_item"  do %>
        <%= link_to "Edit", edit_restaurant_path(restaurant) %>
      <% end %>

    </p>
  </li>

Freitag/restaurant_app/app/views/restaurants/chef_info.html.erb
<h>CHEF: <%= @restaurant&.chef&.name %></h>

Freitag/restaurant_app/app/views/restaurants/edit.html.erb
<%= turbo_frame_tag id="<%=restaurant_#{@restaurant.id}_item"  do %>
  <%= render "form", restaurant: @restaurant %>
<% end %>

Freitag/restaurant_app/app/views/restaurants/index.html.erb
<h1>Hello world</h1>

<h2>
  <% @restaurants.each do |rest| %>
    <p><%= rest.name %></p>
    <p><%= rest.address %></p>
    <p>ChefName: <%= rest.chef&.name %></p>
    <%= link_to "Restaurant", restaurant_path(rest) %>
  <% end %>
</h2>

<p><%= link_to "New Restaurant", new_restaurant_path%></p>

Freitag/restaurant_app/app/views/restaurants/new.html.erb
<%=render "form", restaurant: @restaurants %>

Freitag/restaurant_app/app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<h3>Address: <%= @restaurant.address %></h3>
<h3>Rating: <%= @restaurant.rating %></h3>
<h3>Chef: <%= @restaurant.chef.name %></h3>
<%= link_to "🛠️", edit_restaurant_path(@restaurant) %>
<%= link_to "☠️", restaurant_path(@restaurant), data: {turbo_method: :delete} %>

<%= link_to "More info about Chef", chef_info_restaurant_path(@restaurant.chef) %>

<h2>Review</h2>
<% @restaurant.reviews.each do |review| %>
  <p><%= review.content %></p>
<%  end %>

<div data-controller="formhandler"  data-formhandler-chef-value="<%= @restaurant.chef.name %>">
  <button class="btn btn-primary" data-action="click->formhandler#toggler">Write Review</button>
  <div class="d-none" data-formhandler-target="formwrap">
    <%= form_with model: @restaurant do |f| %>
      <%= f.text_field :content %>
      <%= f.submit %>
    <% end %>
  </div>
</div>



<div id="ra">
  <p>This is a test paragraph for Rails.</p>
  <%= render @restaurant %>
</div>